name: matlab2024a
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - jupyter-matlab-proxy
      # - matlab_kernel
      # - matlabengine==23.2.1
# variables:
#   LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$HOME/MATLAB/bin/glnxa64
