name: matlab2024b
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - pip
  - pip:
      - jupyter-matlab-proxy
      # - matlab_kernel
      # - matlabengine==24.2.2
# variables:
#   LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$HOME/MATLAB/bin/glnxa64
