name: matlab2025a
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - pip
  - pip:
      - jupyter-matlab-proxy
      # - matlab_kernel
      # - matlabengine==25.1.2
# variables:
#   LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$HOME/MATLAB/bin/glnxa64
