Description of divNonUniform
Home > src > matlab_octave > divNonUniform.m
divNonUniform
PURPOSE
Returns a m+2 by m+1 one-dimensional non-uniform mimetic divergence
SYNOPSIS
function D = divNonUniform(k, ticks)
DESCRIPTION
 Returns a m+2 by m+1 one-dimensional non-uniform mimetic divergence
 operator
 Parameters:
                k : Order of accuracy
                ticks : Edges' ticks e.g. [0 0.1 0.15 0.2 0.3 0.4 0.45]
 ----------------------------------------------------------------------------
 SPDX-License-Identifier: GPL-3.0-or-later
 © 2008-2024 San Diego State University Research Foundation (SDSURF).
 See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
 ----------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
div Returns a one-dimensional mimetic divergence operator depending on whether
This function is called by:
div2DNonUniform Returns a two-dimensional non-uniform mimetic divergence operator
div3DNonUniform Returns a three-dimensional non-uniform mimetic divergence operator
SOURCE CODE
function D = divNonUniform(k, ticks)
% Returns a m+2 by m+1 one-dimensional non-uniform mimetic divergence
% operator
%
% Parameters:
%                k : Order of accuracy
%                ticks : Edges' ticks e.g. [0 0.1 0.15 0.2 0.3 0.4 0.45]
% ----------------------------------------------------------------------------
% SPDX-License-Identifier: GPL-3.0-or-later
% © 2008-2024 San Diego State University Research Foundation (SDSURF).
% See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
% ----------------------------------------------------------------------------
    % Get uniform operator without scaling
    D = div(k, length(ticks)-1, 1);
    [m, ~] = size(D);
    % Compute the Jacobian using the uniform operator and the ticks
    if size(ticks, 1) == 1
        J = spdiags((D*ticks').^-1, 0, m, m);
    else
        J = spdiags((D*ticks).^-1, 0, m, m);
    end
    % This is the non-uniform operator
    D = J*D;
end