Description of mimeticB
Home > src > matlab_octave > mimeticB.m
mimeticB
PURPOSE
Returns a m+2 by m+1 one-dimensional mimetic boundary operator
SYNOPSIS
function B = mimeticB(k, m)
DESCRIPTION
 Returns a m+2 by m+1 one-dimensional mimetic boundary operator
 Parameters:
                k : Order of accuracy
                m : Number of cells
 ----------------------------------------------------------------------------
 SPDX-License-Identifier: GPL-3.0-or-later
 © 2008-2024 San Diego State University Research Foundation (SDSURF).
 See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
 ----------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
div Returns a one-dimensional mimetic divergence operator depending on whether
grad Returns a one-dimensional mimetic gradient operator depending on whether
weightsP Returns the m+1 weights of P
weightsQ Returns the m+2 weights of Q
This function is called by:
SOURCE CODE
function B = mimeticB(k, m)
% Returns a m+2 by m+1 one-dimensional mimetic boundary operator
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells
% ----------------------------------------------------------------------------
% SPDX-License-Identifier: GPL-3.0-or-later
% © 2008-2024 San Diego State University Research Foundation (SDSURF).
% See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
% ----------------------------------------------------------------------------
    Q = sparse(diag(weightsQ(k, m, 1)));
    D = div(k, m, 1);
    G = grad(k, m, 1);
    P = sparse(diag(weightsP(k, m, 1)));
    B = Q*D + G'*P;
end