Description of weightsQ
Home > src > matlab_octave > weightsQ.m
weightsQ
PURPOSE
Returns the m+2 weights of Q
SYNOPSIS
function Q = weightsQ(k, m, dx)
DESCRIPTION
 Returns the m+2 weights of Q
 Parameters:
                k : Order of accuracy
                m : Number of cells
               dx : Step size
 ----------------------------------------------------------------------------
 SPDX-License-Identifier: GPL-3.0-or-later
 © 2008-2024 San Diego State University Research Foundation (SDSURF).
 See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
 ----------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
div Returns a one-dimensional mimetic divergence operator depending on whether
This function is called by:
generateWeights Generates a comma-delimited file for weights used by MOLE libray
mimeticB Returns a m+2 by m+1 one-dimensional mimetic boundary operator
SOURCE CODE
function Q = weightsQ(k, m, dx)
% Returns the m+2 weights of Q
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells
%               dx : Step size
% ----------------------------------------------------------------------------
% SPDX-License-Identifier: GPL-3.0-or-later
% © 2008-2024 San Diego State University Research Foundation (SDSURF).
% See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
% ----------------------------------------------------------------------------
    D = div(k, m, dx);
    b = [-1; zeros(m-1, 1); 1]; % RHS
    Q = [1; D(2:end-1, :)'\b; 1];
end