Description of weightsP
Home > src > matlab_octave > weightsP.m
weightsP
PURPOSE
Returns the m+1 weights of P
SYNOPSIS
function P = weightsP(k, m, dx)
DESCRIPTION
 Returns the m+1 weights of P
 Parameters:
                k : Order of accuracy
                m : Number of cells
               dx : Step size
 ----------------------------------------------------------------------------
 SPDX-License-Identifier: GPL-3.0-or-later
 © 2008-2024 San Diego State University Research Foundation (SDSURF).
 See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
 ----------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
grad Returns a one-dimensional mimetic gradient operator depending on whether
This function is called by:
generateWeights Generates a comma-delimited file for weights used by MOLE libray
mimeticB Returns a m+2 by m+1 one-dimensional mimetic boundary operator
weightsP2D Returns the 2mn+m+n weights of P in 2-D
SOURCE CODE
function P = weightsP(k, m, dx)
% Returns the m+1 weights of P
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells
%               dx : Step size
% ----------------------------------------------------------------------------
% SPDX-License-Identifier: GPL-3.0-or-later
% © 2008-2024 San Diego State University Research Foundation (SDSURF).
% See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
% ----------------------------------------------------------------------------
    G = grad(k, m, dx);
    b = [-1; zeros(m, 1); 1]; % RHS
    P = G'\b;
end